### ISSUE TITLE
question: why do attribute classes that are removed in Roma sometimes produce different ODD expressions?

### ISSUE THREAD

**Issue by rvdb** [TEIC/romajs#106]
This is more of a question than a bug report, but when Roma (version 0.2.9) removes attribute classes from an element, this results in different ODD expressions.

For example:

1. select the `tei_all` template
2. select the `<name>` element --> "Attributes"
3. remove the `att.canonical` and `att.datable` attribute classes
4. download ODD file

This results in following declaration for the `<name>` element in the generated ODD file:

        <elementSpec ident="name" mode="change">
          <classes mode="change">
            <memberOf key="att.datable" mode="delete"/>
          </classes>
          <attList>
            <attDef ident="key" mode="delete"/>
            <attDef ident="ref" mode="delete"/>
          </attList>
        </elementSpec>

The removal of the `att.datable` attribute class in Roma generates a `<memberOf mode="delete"/>` element in the ODD file. OTOH, the removal of the `att.canonical` attribute class generates deletions of the individual attributes of that class in `<attDef mode="delete"/>` elements, instead of a `<memberOf key="att.canonical" mode="delete"/>` element.

While both methods of deleting attributes in ODD are equivalent, I'm wondering what's causing this difference. My guess is that "standalone" attribute classes that aren't included in other attribute classes (such as `att.datable` in this example) generates a `<memberOf mode="delete"/>` element. If the attribute class is included in another attribute class (such as `att.canonical` in this example), its attributes are removed individually by `<attDef mode="delete"/>`.

Is this analysis correct?

**Comment by raffazizzi** [comment]
Hi @rvdb, your analysis is correct. Since `att.canonical` is inherited, the attributes that are part of that class must be removed explicitly. In the wacky world of ODD classes, `name` is not a direct member of `att.canonical`, so we can't tell it to not be a member of a class its is not a member of. On the other hand, `name` does inherit `@key` and `@ref`, so we can tell the processor to exclude those.
