### ISSUE TITLE
<datatype> is generated at the wrong place

### ISSUE THREAD

**Issue by rvdb** [TEIC/romajs#110]
This is tested with Roma 0.2.9.

This is a minor issue, but when creating an attribute with Roma, the `<datatype>` element in the generated ODD file is placed after `<valList>`. According to the content model of [`<attDef>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-attDef.html), `<datatype>` should precede `<valList>`.

**Comment by raffazizzi** [comment]
@rvdb I could not replicate in 0.2.9 with the following steps:

- start with TEI minimal
- add a new attribute to `p` called `@test`
- add a couple values
- set datatype to `teidata.name`
- generate ODD

resulting `elementSpec` with `datatype` before `valList`:
```xml
<elementSpec ident="p" mode="change">
  <attList>
    <attDef ident="test" mode="change">
      <datatype>
        <dataRef key="teidata.name"/>
      </datatype>
      <valList type="closed" mode="change">
        <valItem mode="add" ident="uno"/>
        <valItem mode="add" ident="due"/>
      </valList>
    </attDef>
  </attList>
</elementSpec>
```

**Comment by rvdb** [comment]
@raffazizzi Indeed, I can confirm that it works with your steps. Yet, I think I've found the trigger condition: when a description is added to an attribute value, the `<datatype>` element is misplaced.

For example:

- start with TEI minimal
- add a new attribute to p called @test
- add a couple values
- **add a description to an attribute value**
- set datatype to teidata.name
- generate ODD

This produces following ODD file, with `<datatype>` after `<valList>`:

    <elementSpec ident="p" mode="change">
      <attList>
        <attDef ident="test" mode="change">
          <valList mode="change">
            <valItem mode="add" ident="test1">
              <desc versionDate="2020-09-03" xml:lang="en">test</desc>
            </valItem>
            <valItem mode="add" ident="test2"/>
          </valList>
          <datatype>
            <dataRef key="teidata.name"/>
          </datatype>
        </attDef>
      </attList>
    </elementSpec>
