### ISSUE TITLE
File download: extension is always .xml

### ISSUE THREAD

**Issue by martinascholger** [TEIC/romajs#116]
In Firefox (I'm using a windows machine) all the downloaded files have the file extension .xml. I'm pretty sure that when I used Roma in December, the files had the correct file extensions.

**Comment by raffazizzi** [comment]
Confirmed. Was going to blame it on OxGarage, but it seems to work fine when transformed through the OxGarage interface. Will investigate

**Comment by raffazizzi** [comment]
This seems to be ok now (dev)
