### ISSUE TITLE
On elements add/exclude page, add SortByModule

### ISSUE THREAD

**Issue by jamescummings** [TEIC/romajs#12]
On elements add/exclude page, add SortByModule somehow. (maybe have 'Elements' and 'Module' titles that get clicked on? Or just an up/down arrow at each that enables sorting toggle of some sort?)

**Comment by raffazizzi** [comment]
@jamescummings bump in case you're back on the clock

**Comment by jamescummings** [comment]
@raffazizzi Is this live on the mith.us/romajs site? Or where else should I test?

I understand the resistance to adding more UI components...

Does it search or ignore the displayed descriptions? It seems weird to have filter that isn't using all the text available.  Imagine I don't know the TEI very well and I want to find an element by a word in its description?

**Comment by raffazizzi** [comment]
It's not searching on the descriptions. The list is of TEI members (elements, classes, etc) is huge... getting to the member you're looking for needs to be pretty quick and I think searching on descriptions will add a fair bit of noise. This might be something for the user testing phase to determine. 

Will leave this open to deal specifically with the sorting of modules. Will ping you again once a demo is up.
