### ISSUE TITLE
File download: Error message in rng schema

### ISSUE THREAD

**Issue by eafentoulidou** [TEIC/romajs#122]
Hello! The ODD I download is fine, but the rng has only an error message:

<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>

<error msg="Too many nested template or function calls. The stylesheet may be looping." exclass="class pl.psnc.dl.ege.exception.ConverterException" >pl.psnc.dl.ege.exception.ConverterException: Too many nested template or function calls. The stylesheet may be looping.
	at pl.psnc.dl.ege.MultiXslConverter.convert(MultiXslConverter.java:109)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)
</error>

Thanks for developing and improving roma, anyway!

**Comment by raffazizzi** [comment]
Hello @eafentoulidou, would you consider sharing your ODD?

**Comment by eafentoulidou** [comment]
Sure! Here you are. Thank you for the support.
[single_prayer.zip](https://github.com/TEIC/romajs/files/6114236/single_prayer.zip)

**Comment by raffazizzi** [comment]
Thanks, it looks like most of the changed classes where referring to themselves, for example:

```xml
<classSpec ident="att.dimensions" type="atts" mode="change">
  <classes mode="change">
    <memberOf key="att.dimensions"/>
  </classes>
</classSpec>
```

Can you tell me how you made changes to the classes if you remember?

I've edited the ODD and commented out the problematic parts and this should go through.
[single_prayer.zip](https://github.com/TEIC/romajs/files/6118803/single_prayer.zip)

**Comment by eafentoulidou** [comment]
Thank you! It now works.
I made all the changes by clicking the boxes in the web tool.
