### ISSUE TITLE
On element content edit (and similar screens) turn name of element into link to current guidelines ref page?

### ISSUE THREAD

**Issue by jamescummings** [TEIC/romajs#13]
On element content edit (and similar screens) turn name of element into link to current guidelines ref page?
i.e. on <abbr> I should be able to go see the reference page (in a new page target) in order to see all the things about it as it is now?

**Comment by raffazizzi** [comment]
I'm not too sure this is a good idea. The customized element may differ substantially and unpredictably from the current TEI declaration. While Roma serves only TEI at the moment, this hardcoded connections to the TEI Guidelines would complicate if not preclude usage with non-TEI vocabularies.
