### ISSUE TITLE
Roma excludes customization features from download into *.rng and documentation.

### ISSUE THREAD

**Issue by leothecle1967** [TEIC/romajs#130]
I can change attributes and include/exclude elements on the www-application of Roma, but it does not ‎translate and download them into *.rng, *.odd and the documentation files.‎

After having deleted some standard attributes (and created the *.rgn etc. successfully), I wanted to re-‎include (and specify) some of them (_rend_ and a few others) into the element **seg** again.‎

I even deleted all changes to **seg** and compiled my customization of **seg** anew (after reloading ‎the site, rebooting the computer, deletion of all cookies), unsuccessfully. I can neither re-include nor ‎include _rend_ and others into **seg** again.‎

Is this my mistake (what should hence be avoided)?‎

Attachment: successfully created *.rng etc. that Roma does not allow to be customized/enhanced any ‎more. Screenshot: including _rend_ from which the *.rng etc. was downloaded.‎
[Roma_problems.zip](https://github.com/TEIC/romajs/files/6642115/Roma_problems.zip)

**Comment by lb42** [comment]
Rng is the output from Roma. To get different rng you need to change the input, ie the source odd file.

**Comment by leothecle1967** [comment]
Oh thank you! Yes: I take an *.odd as input to Roma, which works well. I change its customization, and I expect that the changes that are visible in (and hence well formed for) Roma will be translated into the new *.rng output. I even see the changes in the new output *.odd. In the case of the attribute(s) _rend_ (and others) in **seg** (and **ab**) they do not appear in the new *.rng output file.

**Comment by lb42** [comment]
In your haggadah.odd file, I see the following:
~~~~
<attDef ident="rend" mode="delete"><valList type="closed" mode="change"><valItem mode="add" ident="center"/><valItem mode="add" ident="left_indent"/><valItem mode="add" ident="right_indent"/><valItem mode="add" ident="inline_spaced"/></valList></attDef>
~~~~

This means that the attribute @rend is to be deleted. The valList which (I assume) you have added does not affect that.

 If I change 'mode="delete"' to 'mode="change", the change you are trying (I think) to produce works fine

This may be something strange in the Roma interface -- I am only looking at the ODD source code and processing it with oXygen.

**Comment by leothecle1967** [comment]
thank you very much! Great! You solved my problem! I edit the odd and oxgarage makes rng files. Thank you indeed!
