### ISSUE TITLE
I18N !!

### ISSUE THREAD

**Issue by lb42** [TEIC/romajs#134]
Old Roma for all its faults could be used by non-English speakers. Is there any timescale for a non-English version of new roma? What needs to be tweaked in the sources to produce e.g. a French version? (I would like to use it in teaching so this is really holding me up)

**Comment by lb42** [comment]
no progress on this one?

**Comment by lb42** [comment]
see pull request for i18n-fr branch

**Comment by raffazizzi** [comment]
As of today we have DE, FR, IT. Closing for now
