### ISSUE TITLE
attribut n dans entry

### ISSUE THREAD

**Issue by WGBS2** [TEIC/romajs#149]

**Comment by WGBS2** [comment]
I have been trying to add n to entry with no success. I validate it, but it is not present in odd or rng downloaded

**Comment by raffazizzi** [comment]
Hello @WGBS2 , can you say a little bit more? The `@n` attribute should already be allowed on `entry`. What preset are you starting from and what are you doing to add n to entry? If I can reproduce the problem, I will be happy to address it as soon as possible.

**Comment by WGBS2** [comment]
Hi, Thanks for your answer. We built a specific odd for the purposes of encoding this 17th c dictionary. The attribute @n'was discarded. We have been using an online tool provided by the university of Grenoble to correct content and its outputs add an 'n' attribute to <entry> so as to order the information. This obviously shows up as an error so I uploaded the odd to roma beta and put back 'n'. It shows as being present within Roma, but at download it is never there. I tested by removing and replacing @type, which worked perfectly. But the non-presence of @n remains a mystery.

**Comment by WGBS2** [comment]
I don't seem to be able to send the odd

**Comment by WGBS2** [comment]
<img width="752" alt="Capture d’écran 2023-06-07 à 16 20 00" src="https://github.com/TEIC/romajs/assets/16626111/be38faac-b370-493d-b401-3696084ea484">
<img width="677" alt="Capture d’écran 2023-06-07 à 16 19 44" src="https://github.com/TEIC/romajs/assets/16626111/fd4aae45-6ee8-4cf1-9542-2411a704942e">

**Comment by raffazizzi** [comment]
I think that to solve this problem I will need to know how `@n` was originally removed from `<entry>`. Can you send the ODD to [rviglian@umd.edu](mailto:rviglian@umd.edu) ?

**Comment by raffazizzi** [comment]
I was able to replicate the issue; this is a bug.
* start with TEI All
* remove `@n` from `entry`
* save ODD
* upload ODD
* restore `@n` on `entry`
* save new ODD --> `@n` still has `mode="delete"`
