### ISSUE TITLE
HTML documentation incompletely translated 

### ISSUE THREAD

**Issue by lb42** [TEIC/romajs#154]
In the HTML file generated for an ODD specifying French as the language of documentation the labels in the tables (e.g. "Member of", "Contained by" etc.) are still in English. This doesn't happen for the online documentation, e.g. at https://tei-c.org/release/doc/tei-p5-doc/fr/html/ref-abbr.html which translates these phrases  correctly.

**Comment by raffazizzi** [comment]
@lb42 This seems to happen just the same in TEIGarage with these attributes on `schemaSpec`: `<schemaSpec ident="tei_fr_ex" xml:lang="fr" prefix="tei_" targetLang="fr" docLang="fr">`

The TEI Stylesheets for XHTML output and the official TEI Guidelines are different, so I will raise this to the Stylesheets repo.

**Comment by raffazizzi** [comment]
Figured out how to pass this value via parameter to TEIGarage. Still working on it, but I am re-opening this issue.
