### ISSUE TITLE
HTML description lacks links

### ISSUE THREAD

**Issue by lb42** [TEIC/romajs#155]
In the HTML file generated for an ODD specifying French as the language of documentation, the description for each element lacks the links to the Guidelines, which appear just as prose. 

In the online version the source says <span class="label">&lt;abbr&gt; </span>(abréviation) contient une abréviation quelconque. [<a class="link_ptr" href="[CO.html#CONAAB](view-source:https://tei-c.org/release/doc/tei-p5-doc/fr/html/CO.html#CONAAB)" title="Abbreviations and Their Expansions"><span class="headingNumber">3.6.5 </span>Abbreviations and Their Expansions</a>]

In the generated version I see <span class="label">&lt;abbr&gt; </span>(abréviation) contient une abréviation quelconque. [3.6.5. Abbreviations and Their Expansions]

Interestingly, this doesn't happen when generating DOCX or PDF, both of which do include the links

**Comment by raffazizzi** [comment]
Dear Lou, these transformations are handled by TEIGarage, so the TEI Stylesheets may be to blame. I'll take a look to see if there are some parameters Roma is not setting correctly -- if not, I'll raise this issue elsewhere.

**Comment by lb42** [comment]
It seems odd (ha!) that the transformations to docx and pdf, presumably also handled by TEIgarage, don't have this problem. So I think some parameter used by the stylesheets is getting set differently.
