### ISSUE TITLE
Incompletely translated button

### ISSUE THREAD

**Issue by lb42** [TEIC/romajs#157]
The message associated with the "Browse" button when loading an ODD file is "No File Selected" deven when the language of all other parts of the interface is French.
![noFileSelected](https://github.com/TEIC/romajs/assets/660724/2531b12c-0eea-4df0-868b-9eeebe64518e)

**Comment by raffazizzi** [comment]
@Lou, that button is rendered by your browser so it will show up in the language of your browser.
