### ISSUE TITLE
RELAXNG Schema in compact syntax should be a plain text file not a zip archive

### ISSUE THREAD

**Issue by lb42** [TEIC/romajs#159]
When I try to download my customization as RNC, roma sends me a file which can't be read by the browser, nor by oXygen. Looking at it with emacs, I see that the file produced is actually a zip archive with two files : one called document.rnc and the other called .nfs[meaninglessHexString]. If I unpack the archive, and use document.rnc as the schema everything is fine, but surely this is not the way the interface should behave! I am using firefox on linux.

**Comment by lb42** [comment]
I am reopening this rather than start a new issue for this comparatively minor annoyance. Downloading a schema in relax compact syntax now produces a file with the extension .zip -- which is actually (sfaics) a plain text file. It works fine when specified explicitly as the schema for oXygen -- but oxygen by default won't look at it since .zip is not one of the file extensions expected for a schema. Why not send a file with the extension .rnc ?

**Comment by cboulanger** [comment]
Under certain conditions (don't know which), the w3c schema download is also a ZIP-File containing a "document.xsd" and a "xml.xsd" file. The download has a "w3c" extension so the result is an unreadable binary file.
