### ISSUE TITLE
Changing content model doesn't seem to be saved to ODD?

### ISSUE THREAD

**Issue by jamescummings** [TEIC/romajs#16]
Changing the content model doesn't seem to be saved to ODD?

Go to element, delete a content model (maybe it is only if you end up with an invalid one?) save ODD, change doesn't exist. If I'm just doing it wrong, needs to be clearer.

**Comment by raffazizzi** [comment]
I believe this may be fixed now. Would you mind testing again? Make sure to hard refresh to get the latest JS

**Comment by raffazizzi** [comment]
This appears to be resolved now, closing. Please reopen (or start new issue) if you notice this again.
