### ISSUE TITLE
Uploading an ODD fails

### ISSUE THREAD

**Issue by rettinghaus** [TEIC/romajs#172]
When I try to upload an ODD I just get the error

> JSON.parse: unexpected character at line 1 column 1 of the JSON data

This happens also with official customizations.

**Comment by gerritbruening** [comment]
When I try to upload a `.odd` file I get the following response:

![image](https://github.com/user-attachments/assets/09caa1e4-3459-45be-a9d8-06cecdc65e7d)

Is this the same issue?

**Comment by rettinghaus** [comment]
I guess. It seems to be browser dependent.

**Comment by gerritbruening** [comment]
> I guess. It seems to be browser dependent.

I have the same impression. Firefox shows the behavior you described above, while Chrome shows the behavior I described.

**Comment by raffazizzi** [comment]
Thank you both for reporting this major bug! Just made [a hotfix release (v 1.1.2)](https://github.com/TEIC/romajs/releases/tag/v1.1.2); it should show up at https://roma.tei-c.org shortly.

**Comment by raffazizzi** [comment]
@gerritbruening it looks like TEI Garage (which handles pre- and post- roma transformations) is down. https://downforeveryoneorjustme.com/teigarage.tei-c.org?proto=https

I've notified the infrastructure group.

**Comment by raffazizzi** [comment]
@gerritbruening looks like it's back!

**Comment by gerritbruening** [comment]
Confirmed, thanks!

**Comment by michaelpilarski** [comment]
@raffazizzi I think TEI Garage is down again:
https://downforeveryoneorjustme.com/teigarage.tei-c.org?proto=https

I will notify the infrastructure group.

**Comment by michaelpilarski** [comment]
@raffazizzi Nevermind, it's back. Thanks @peterstadler !
