### ISSUE TITLE
Improve user feedback on loading

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/romajs#27]
Is it possible to load some features while the rest gets loaded?

**Comment by raffazizzi** [comment]
Explore using Oboe.js to stream p5subset.json and start displaying at least member list (possibly with add/remove operations) 
http://oboejs.com/

**Comment by jamescummings** [comment]
Are there changes to p5subset that could be done to make this more efficient?

**Comment by raffazizzi** [comment]
At the moment p5subset.json is fairly coupled with RomaJS's internal data model, so it *should* already be in a shape optimized for this. The problem I'm hoping to solve (possibly with streaming) is getting the user going while we wait for the customization XSLT to complete and data is downloaded from OxGarage

Ideal outcomes:
* displaying information _before_ the entirety of p5subset.json is downloaded to the user's computer (how realistic this is, I yet have to determine, but oboe seems promising) 
* enable some read-only operations, such as scrolling through list of "members" (elements, classes, datatypes, etc) and allow filtering of whatever data has already been download (this should increase quickly)
* if this approach is successful, allow minimal write operations such as toggling members and modules.
