### ISSUE TITLE
search placeholder text out of place 

### ISSUE THREAD

**Issue by peterstadler** [TEIC/romajs#54]
on Safari 12.0.3 (MacOS High Sierra) it looks like
<img width="283" alt="bildschirmfoto 2019-02-25 um 13 49 52" src="https://user-images.githubusercontent.com/2247936/53338735-bae91280-3904-11e9-9e36-f5b204c5bc71.png">

On Chrome and Firefox it looks ok.

**Comment by raffazizzi** [comment]
Seems fixed (Safari 14.1.1)
