### ISSUE TITLE
Safari: doing a browser reload will break the page

### ISSUE THREAD

**Issue by peterstadler** [TEIC/romajs#55]
endless spinning without caption …
nothing appears …

[tested with Safari 12.0.3 on MacOS High Sierra]

**Comment by raffazizzi** [comment]
In order to support page reloads, the data is stored in the browser's localstorage. Safari only allows a small amount of storage per site, which is why the data is not available on refresh.

As a reference, an error is emitted to the console:
```
Error storing data QuotaExceededError: The quota has been exceeded.
```

Possible solutions:
 * warn on page reload (not sure this is possible)
 * avoid blank page of death with a message after reload (the data, however, will be lost nonetheless)

**Comment by raffazizzi** [comment]
It would also be possible to compress the state before persisting it.

I looked at this: https://github.com/rt2zz/redux-persist-transform-compress and it prevented the Quota error in Safari, unfortunately it doesn't seem to rehydrate it correctly (or quickly enough) so it causes a reload to be broken on all systems. Will need to experiment more.

I could try to write my own compressor for redux-persist using pako https://github.com/nodeca/pako

A last ditch strategy would be only persisting non-static parts of the state, such as the json customization and re-obtain xml and p5subset data on reload. (this could be driven by a flag that indicates whether the quota has been exceeded)

**Comment by raffazizzi** [comment]
Update: got redux-persist-transform-compress working, but it adds substantial lag. Next I'll experiment with compressing only part of the state

**Comment by peterstadler** [comment]
gosh, I wouldn't think it's that can of worms!

**Comment by raffazizzi** [comment]
Hey @peterstadler could you do a quick test to see if this is still the case 4 years later?

**Comment by raffazizzi** [comment]
Note to self: consider using the indexed db API https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

**Comment by peterstadler** [comment]
Just tested again and it (reload of https://roma.tei-c.org/members) still fails for Safari 17.3.1 on MacOS 14.3.1:

![Bildschirmfoto 2024-03-19 um 14 22 28](https://github.com/TEIC/romajs/assets/2247936/e98fc173-7a2d-4a6d-bf0a-6490d22cc0b0)

**Comment by peterstadler** [comment]
(Tested this with Firefox 132.0.1 on the same Mac and it works)

**Comment by raffazizzi** [comment]
Thanks. This will need a big change of strategy so it may sty broken for a while longer.

**Comment by raffazizzi** [comment]
Closed by https://github.com/TEIC/romajs/commit/3122362cb4c3c962a4959a131ab53ccb4a0ddae3. Thanks @BWangy !
