### ISSUE TITLE
switching documentation language causes infinite loop

### ISSUE THREAD

**Issue by peterstadler** [TEIC/romajs#62]
The issue is a little unpredictable because I couldn't figure what actually triggers it. Hence I made that little screencast for you to enjoy: https://www.dropbox.com/s/0vdi75ggyvzp36z/romajs-bug.mov?dl=0  :)

Problem is, that sometimes when changing the documentation language the loader progress bar just does not stop thus preventing you to move on to "customize ODD" (which is then still greyed out). NB: the call to (and response from) oxgarage seems to be ok, it's just not picked up?!

**Comment by peterstadler** [comment]
I was trying with Chrome and Firefox and although all requests return a 200 status code, Chrome shows a "(failed)" with "net::ERR CONTENT LENGTH MISMATCH" in the tool tip just before the issue occurs. 
So, it might be an issue with the mith server hosting the fake data directory?

**Comment by raffazizzi** [comment]
The fake data directory is not in use anymore and I couldn't reproduce the problem today. Could you give it another try? Thanks!

**Comment by peterstadler** [comment]
unable to reproduce, closing …
