### ISSUE TITLE
color code for including/excluding modules

### ISSUE THREAD

**Issue by peterstadler** [TEIC/romajs#64]
I was teaching an ODD class last week and introduced the participants to the new Roma :) 

Their spontaneous reaction to the red/green colouring was just the opposite to how it works now. They were expecting the green labeled modules to be included (at present) and the red ones to be excluded. It looks like they were interpreting the colours as status, not as actions …

**Comment by raffazizzi** [comment]
We may want to collect more data on this. I'm reluctant to add a green background to a button with an "x" on it. Perhaps we can choose less 'marked' colors and let the icons be the primary indication of what the button does?

For reference, these are the buttons we're talking about:

![Screenshot from 2019-09-13 11-24-36](https://user-images.githubusercontent.com/144770/64852191-326c5e00-d619-11e9-9752-2a9ec991c83d.png)

**Comment by ebeshero** [comment]
I'll test this with my students this week and next and leave some comments here...

**Comment by ebeshero** [comment]
@raffazizzi Just an update: I showed my students how to use Roma JS to start an ODD customization in class, and I have one student project team who's working on it starting this weekend. When I showed it in class, I understood that the red X meant you were choosing to remove something, and we worked module-by-module to make that decision first. I think that signalling is clear and precise!

After doing a lot of cutting, the idea that you can ADD an element to a customization is also clear with the green plus sign. Now, I say this, but I pretty much demo'd it to my students in class. I don't have data QUITE yet on how this looks when they start doing it themselves. I'll know more soon! The project in my class working on an ODD customization starting with Roma JS is here: https://github.com/haggis78/BreconChurch
