### ISSUE TITLE
duplicating an existing attribute produces incorrect ODD

### ISSUE THREAD

**Issue by peterstadler** [TEIC/romajs#66]
## How to reproduce

* start with minimal schema and build up
* modify attributes of `<unclear>` by adding a new `@hand` attribute (see screenshot)
* Download customization

![Bildschirmfoto 2019-09-11 um 12 57 11](https://user-images.githubusercontent.com/2247936/64691963-420e6a00-d494-11e9-84e5-56ea6e367d79.png)

## Resulting ODD snippet

```xml
<elementSpec ident="unclear" mode="change">
  <attList>
    <attDef ident="hand" mode="add" usage="opt">
      <desc versionDate="2018-06-15" xml:lang="en">points to a <gi>handNote</gi> element
        describing the hand considered responsible for the content of the element
        concerned.</desc>
    </attDef>
  </attList>
</elementSpec>
```

## Problem 

This attribute lacks a datatype and/or a valList

## What did I expect

Although the description says "Duplicate an existing attribute" I'd expect it to simply point to that attribute via an `<attRef>`, like 

```xml
<attRef name="hand" class="att.written"/>
```

**Comment by raffazizzi** [comment]
@peterstadler I didn't think of attRef. How does this sound:

If there are no modifications to the copied attribute, use `attRef`
Otherwise create new `attDef` with changed content (starting off the original one)
