### ISSUE TITLE
activating att.global.responsibility in Absolutely Bare setup --> error

### ISSUE THREAD

**Issue by JSchaeuble** [TEIC/romajs#71]
Maybe someone can reproduce this error.
I started a schema from "TEI Absolutely Bare" and added some further elements. Inbetween I saved a couple of times, continued later (by uploading it again) and everything worked wonderfully.

But as soon as I activate the Attribute Class att.global.responsibility I can not download the ODD anymore. I started it also from scratch, not adding any other elements or attributes first. 

Error:
```
Roma JS is still in alpha. The following error occurred:
Uncaught TypeError: Cannot read property 'removeChild' of null
```

if I activate some elements and attribute classes before, the error varries, but I have not managed to produce an exportable ODD starting from Absolutely Bare AND including att.global.responsibility.

**Comment by raffazizzi** [comment]
Hello @JSchaeuble both @peterstadler and I cannot reproduce this error. I have made updates since you reported this issue. Could you try again?

**Comment by raffazizzi** [comment]
Closing before of inactivity. @JSchaeuble if this is still an issue for you, please re-open and include detailed steps to reproduce.
