### ISSUE TITLE
Infer ODD from TEI upload

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/romajs#72]
On the home page, add an option to start from a TEI file instead of an ODD. Is there an [oddbyexample.xls](https://github.com/TEIC/Stylesheets/blob/94b9a4b4bdc7500a2a371149f1e685e765690205/tools/oddbyexample.xsl) endpoint in OxGarage and can we add it?

**Comment by sydb** [comment]
Note, though, that if the uploaded TEI file contains a `<schemaRef>` that refers to an ODD (how would you know?) or a `<schemaSpec>`, Romaβ should use that. (How it would choose among multiple is a bit of a thorny issue.)

**Comment by jamescummings** [comment]
Also the strength of oddbyexample is when you point it at a whole directory of files. ;-) I could envision a similar thing (upload a zip of many TEI files)... but I'm wondering if that is really worth the effort.

**Comment by lb42** [comment]
Coincidentally I have been using oddbyexample today. The parameters seem to be broken. Is it worth raising an issue on the stylesheet repo?

**Comment by raffazizzi** [comment]
Declaring this out of scope for the foreseeable future.
