### ISSUE TITLE
HTML documentation title and author weirdness

### ISSUE THREAD

**Issue by ebeshero** [TEIC/romajs#77]
One of my students is making an ODD with RomaJS and we just took at look at her custom HTML documentation. All she did was indicate that she is the author of this ODD customization, and well, it turned out like this:

https://htmlpreview.github.io/?https://github.com/haggis78/BreconChurch/blob/master/ODD/Brecon_Church_TEIODD..html

The ODD is here: https://github.com/haggis78/BreconChurch/blob/master/ODD/tei_brecon.odd

I'm not sure if this is a TEI Stylesheets issue or something easy to fix over here in Roma JS?
@raffazizzi

**Comment by raffazizzi** [comment]
I noticed that too, but I think it's a Stylesheets issue: the same happens with unchanged customization like TEI Minimal
