### ISSUE TITLE
When defining content model, reference hidden (Firefox) 

### ISSUE THREAD

**Issue by pboot** [TEIC/romajs#82]
I try to create a content model. I click references, because I want to add a reference to an element. Then I click elementRef. The elementRef appears but is almost completely hidden under the grey rectangle, making it quite non-intuitive what the next steps should be.  

![image](https://user-images.githubusercontent.com/4853271/68296975-2a1f2500-0096-11ea-9e2b-ed5a6b75003f.png)

**Comment by raffazizzi** [comment]
Hi @pboot is this still an issue? I just checked on Firefox 110.0.1 and it worked fine.

![Peek 2023-03-09 11-50](https://user-images.githubusercontent.com/144770/224096740-1e99dd5a-e15e-47a2-aa46-043bd9fe5661.gif)

**Comment by pboot** [comment]
No, it works fine now.
