### ISSUE TITLE
Error on removing undefined element

### ISSUE THREAD

**Issue by pboot** [TEIC/romajs#84]
I try to remove an element (=uncheck in member list) that I added but for which I have not yet defined description, content or anything else. 

The result is an error:

Oh-oh... Something went wrong
Roma is still in beta. The following error occurred:
TypeError: localEl is undefined

![image](https://user-images.githubusercontent.com/4853271/68297753-ffce6700-0097-11ea-8b0a-b8294f889707.png)

**Comment by rvdb** [comment]
I see the same error when:
1. An new empty element definition is created in Roma
2. The ODD file is stored
3. The Odd file is reloaded in Roma
4. The new empty element definition is populated in Roma
5. The ODD file is stored again

It does not happen when steps 2-3 are skipped, and the new element definition is populated immediately in Roma. 

Yet, the resulting `<elementSpec>` element does not have a `<content>` element (see https://github.com/TEIC/romajs/issues/86)
