### ISSUE TITLE
Content missing for new element in ODD

### ISSUE THREAD

**Issue by pboot** [TEIC/romajs#86]
I create a new element with content as in the image:

![image](https://user-images.githubusercontent.com/4853271/68299375-dca5b680-009b-11ea-9d23-a79a95710ecd.png)

The generated ODD does not define the content:

        <elementSpec ident="glossGrp" ns="http://www.example.org/ns/tei_minimal" mode="add">
          <desc versionDate="2019-11-06" xml:lang="en">Groups related glosses from different
            mss</desc>
          <classes>
            <memberOf key="att.pointing"/>
          </classes>
          <attList/>
        </elementSpec>
  
Am I missing something? Is there something wrong with the content?

**Comment by raffazizzi** [comment]
Fixed in 3.0.0
