### ISSUE TITLE
Unable to use TEI Simple as a starting point

### ISSUE THREAD

**Issue by NickLaiacona** [TEIC/romajs#89]
When you first begin and are prompted to choose an ODD file, if you select TEI Simple, you encounter the following error:

![Screen Shot 2020-02-20 at 2 04 45 PM](https://user-images.githubusercontent.com/11439/74969240-2ebfdd00-53ea-11ea-9322-a4a70ba5a289.png)

Tried several other ODDs, it seems to be something to do with TEI Simple in particular.

**Comment by peterstadler** [comment]
I can confirm the issue.
Problem is in the underlying OxGarage transformation that should return JSON from the TEI XML source but chokes on the referenced images (in the ODD file). There was an issue at https://github.com/TEIC/oxgarage/issues/29 which seems to be resolved now.

@raffazizzi isn't the second conversion parameter implemented in Roma yet or is this another issue?
