### ISSUE TITLE
comment saying 'required' appears between moduleRefs

### ISSUE THREAD

**Issue by jamescummings** [TEIC/romajs#95]
Starting from tei_all I created a customisation for a project, and the ODD contains an xml comment saying 'required' between certain moduleRef elements. I'm guessing this might be a carry-over from the template ODD saying this after the 'tei' module.

**Comment by raffazizzi** [comment]
Yes those comments are in the ODD template. And I wouldn't want Roma to mess with comments in an existing ODD. So either I bring this up with the council to update tei_all.odd to remove them, or they'll remain there after processing. What do you suggest?

**Comment by jamescummings** [comment]
I don't actually think the comments saying 'required' are really that helpful in https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_all.odd 
And once customisation has been done to remove elements from those modules, it just looks weird.
So I'd suggest we remove them from there.

**Comment by raffazizzi** [comment]
Opened issue on TEIC/TEI https://github.com/TEIC/TEI/issues/1987
