### ISSUE TITLE
When I've deleted 'teiCorpus' why does customisation still have it as a possible starting point?

### ISSUE THREAD

**Issue by jamescummings** [TEIC/romajs#96]
I created a customisation starting from tei_all, but I deleted teiCorpus, cuz, you know, who uses that. And the start attribute of schemaSpec still has teiCorpus as a starting possibility. I'm guessing that comes from the original template ODD but seems wrong.

Should there be a step when deselecting any element that warns if a start element has been removed? And/or removes it from start and warns that is empty, thus broken? (Can't be a list of specific elements, obvs, since one might be making a customisation that starts anywhere.)

**Comment by lb42** [comment]
Possibly. But that's a level of sophistication/handholding beyond what ODD processors currently provide. If you delete element X which is mandatory within the content of element Y, ODD processors don't warn you about that either. You are expected to know what you're doing when you delete elements, you snowflake! And if you were making a customization which "starts anywhere", you'd need to change the @start attribute on the schemaSpec in your ODD anyhow, so why wouldn't you remove teiCorpus from there at the same time?

**Comment by raffazizzi** [comment]
It shouldn't be hard to implement. Will add it to the queue. The resulting schema is valid, though, right? (just so that I know how urgently I need to address this)

**Comment by jamescummings** [comment]
@raffazizzi Yes, the resulting ODD and Schema are valid.

@lb42 Yes, really only a feature enhancement for RomaBeta. It seems reasonable that the start attribute really should only contain one or more element idents that are available in that customisation. It is probably only in creating the compiled ODD that this is easy to figure out. I'm not asking for the more complicated case of getting a warning when deleting element X which is required in content of Y. Though I suppose one could, on any element deletion, check whether there was any content model which had it as required content. But definitely not what I was asking for!
