### ISSUE TITLE
"ISO  Schematron constraints" transformation is broken

### ISSUE THREAD

**Issue by rvdb** [TEIC/romajs#97]
The option for downloading "ISO Schematron constraints" in Roma beta is producing an error message. Apparently, the processing pipeline is referring to a non-existent file `/usr/local/common/functions.xsl`.

Steps to reproduce:

1. Select any TEI customization template
2. Choose "Download" > "ISO Schematron constraints"
3. Open the downloaded file

While a file is being generated, it contains following error message (and duplicate XML declaration):

    <?xml version="1.0" encoding="UTF-8"?>
    <?xml version="1.0" encoding="UTF-8"?>
    
    
    <error msg="I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)" exclass="class pl.psnc.dl.ege.exception.ConverterException" >pl.psnc.dl.ege.exception.ConverterException: I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
      at pl.psnc.dl.ege.MultiXslConverter.convert(MultiXslConverter.java:109)
      at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
      at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
      at java.lang.Thread.run(Thread.java:748)
    </error>

**Comment by raffazizzi** [comment]
Unfortunately this depends on an Oxgarage issue: https://github.com/TEIC/oxgarage/issues/14
Perhaps I'll remove the download option until there's a fix

**Comment by raffazizzi** [comment]
This seems to be working now
